# Generated by Django 4.2.30 on 2026-04-16 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('form_type', models.CharField(choices=[('onboarding', 'Onboarding'), ('daily', 'Daily'), ('weekly', 'Weekly')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['form_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CheckInQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('short_text', 'Short Text'), ('long_text', 'Long Text'), ('number', 'Number'), ('yes_no', 'Yes / No'), ('dropdown', 'Dropdown'), ('photo', 'Photo Upload'), ('video', 'Video Upload')], max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=1)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='progress.checkinform')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CheckInQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='progress.checkinquestion')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
