# Generated by Django 4.2.30 on 2026-04-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='is_complete',
            field=models.BooleanField(default=True),
        ),
    ]
