# Generated by Django 4.2.30 on 2026-04-16 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0002_exerciselibraryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_specific_workout_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='is_template',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='source_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_versions', to='workouts.workoutplan'),
        ),
    ]
