from django.urls import path
from django.contrib.auth import views as auth_views
from .dashboard_views import (
    landing_page,
    trainer_login_page,
    trainer_logout_page,
    trainer_hub_page,
    trainer_dashboard,
    trainer_dashboard_home,
    trainer_client_detail_page,
    trainer_workout_plans_page,
    trainer_workout_plan_detail_page,
    trainer_nutrition_plans_page,
    trainer_nutrition_plan_detail_page,
    trainer_checkin_forms_page,
    trainer_checkin_form_detail_page,
    trainer_settings_page,
    dashboard_update_profile,
    dashboard_delete_account,
    dashboard_check_slug,
    dashboard_pricing_save,
    dashboard_pricing_delete,
    trainer_activity_page,
    trainer_site_page,
    dashboard_create_client,
    dashboard_delete_client,
    dashboard_assign_workout_plan,
    dashboard_assign_nutrition_plan,
    dashboard_unassign_workout_plan,
    dashboard_unassign_nutrition_plan,
    dashboard_create_exercise_library_item,
    dashboard_update_exercise_library_item,
    dashboard_delete_exercise_library_item,
    dashboard_duplicate_exercise_library_item,
    dashboard_create_workout_plan,
    dashboard_duplicate_workout_plan,
    dashboard_update_workout_plan,
    dashboard_delete_workout_plan,
    dashboard_create_workout_day,
    dashboard_update_workout_day,
    dashboard_delete_workout_day,
    dashboard_add_exercise_to_day,
    dashboard_update_exercise,
    dashboard_delete_exercise,
    dashboard_create_nutrition_plan,
    dashboard_update_nutrition_plan,
    dashboard_delete_nutrition_plan,
    dashboard_duplicate_nutrition_plan,
    dashboard_create_food_library_item,
    dashboard_update_food_library_item,
    dashboard_delete_food_library_item,
    dashboard_duplicate_food_library_item,
    dashboard_create_nutrition_meal,
    dashboard_update_nutrition_meal,
    dashboard_delete_nutrition_meal,
    dashboard_add_food_to_nutrition_meal,
    dashboard_delete_nutrition_meal_item,
    dashboard_create_checkin_form,
    dashboard_update_checkin_form,
    dashboard_delete_checkin_form,
    dashboard_create_checkin_question,
    dashboard_update_checkin_question,
    dashboard_delete_checkin_question,
)

urlpatterns = [
    path("", landing_page, name="landing-page"),
    path("portal/login/", trainer_login_page, name="trainer-login-page"),
    path("portal/logout/", trainer_logout_page, name="trainer-logout-page"),

    # Phase 10 — /dashboard/ is now the GymFlow Hub.
    # Workouts has moved to /dashboard/workouts/ but keeps its original
    # url-name ("trainer-dashboard-home") so existing {% url %} refs
    # across templates resolve without a fleet-wide edit.
    path("dashboard/", trainer_hub_page, name="trainer-hub-page"),
    path("dashboard/workouts/", trainer_dashboard_home, name="trainer-dashboard-home"),

    path("dashboard/clients/", trainer_dashboard, name="trainer-dashboard"),
    path("dashboard/clients/<int:client_id>/", trainer_client_detail_page, name="trainer-client-detail"),
    path("dashboard/clients/<int:client_id>/delete/", dashboard_delete_client, name="dashboard-delete-client"),

    path("dashboard/create-client/", dashboard_create_client, name="dashboard-create-client"),
    path("dashboard/assign-workout-plan/", dashboard_assign_workout_plan, name="dashboard-assign-workout-plan"),
    path("dashboard/assign-nutrition-plan/", dashboard_assign_nutrition_plan, name="dashboard-assign-nutrition-plan"),
    path("dashboard/clients/<int:client_id>/unassign-workout/", dashboard_unassign_workout_plan, name="dashboard-unassign-workout-plan"),
    path("dashboard/clients/<int:client_id>/unassign-nutrition/", dashboard_unassign_nutrition_plan, name="dashboard-unassign-nutrition-plan"),

    # Workouts — list page kept as alias of the home for old bookmarks.
    path("dashboard/workout-plans/", trainer_workout_plans_page, name="trainer-workout-plans-page"),
    path("dashboard/workout-plans/create-exercise/", dashboard_create_exercise_library_item, name="dashboard-create-exercise-library-item"),
    path("dashboard/workout-plans/exercises/<int:exercise_id>/update/", dashboard_update_exercise_library_item, name="dashboard-update-exercise-library-item"),
    path("dashboard/workout-plans/exercises/<int:exercise_id>/delete/", dashboard_delete_exercise_library_item, name="dashboard-delete-exercise-library-item"),
    path("dashboard/workout-plans/exercises/<int:exercise_id>/duplicate/", dashboard_duplicate_exercise_library_item, name="dashboard-duplicate-exercise-library-item"),
    path("dashboard/workout-plans/create/", dashboard_create_workout_plan, name="dashboard-create-workout-plan"),
    path("dashboard/workout-plans/<int:plan_id>/", trainer_workout_plan_detail_page, name="trainer-workout-plan-detail"),
    path("dashboard/workout-plans/<int:plan_id>/duplicate/", dashboard_duplicate_workout_plan, name="dashboard-duplicate-workout-plan"),
    path("dashboard/workout-plans/<int:plan_id>/update/", dashboard_update_workout_plan, name="dashboard-update-workout-plan"),
    path("dashboard/workout-plans/<int:plan_id>/delete/", dashboard_delete_workout_plan, name="dashboard-delete-workout-plan"),
    path("dashboard/workout-plans/<int:plan_id>/create-day/", dashboard_create_workout_day, name="dashboard-create-workout-day"),
    path("dashboard/workout-plans/<int:plan_id>/days/<int:day_id>/update/", dashboard_update_workout_day, name="dashboard-update-workout-day"),
    path("dashboard/workout-plans/<int:plan_id>/days/<int:day_id>/delete/", dashboard_delete_workout_day, name="dashboard-delete-workout-day"),
    path("dashboard/workout-plans/<int:plan_id>/add-exercise/", dashboard_add_exercise_to_day, name="dashboard-add-exercise-to-day"),
    path("dashboard/workout-plans/<int:plan_id>/exercises/<int:exercise_id>/update/", dashboard_update_exercise, name="dashboard-update-exercise"),
    path("dashboard/workout-plans/<int:plan_id>/exercises/<int:exercise_id>/delete/", dashboard_delete_exercise, name="dashboard-delete-exercise"),

    path("dashboard/nutrition-plans/", trainer_nutrition_plans_page, name="trainer-nutrition-plans-page"),
    path("dashboard/nutrition-plans/create/", dashboard_create_nutrition_plan, name="dashboard-create-nutrition-plan"),
    path("dashboard/nutrition-plans/foods/create/", dashboard_create_food_library_item, name="dashboard-create-food-library-item"),
    path("dashboard/nutrition-plans/foods/<int:food_id>/update/", dashboard_update_food_library_item, name="dashboard-update-food-library-item"),
    path("dashboard/nutrition-plans/foods/<int:food_id>/delete/", dashboard_delete_food_library_item, name="dashboard-delete-food-library-item"),
    path("dashboard/nutrition-plans/foods/<int:food_id>/duplicate/", dashboard_duplicate_food_library_item, name="dashboard-duplicate-food-library-item"),
    path("dashboard/nutrition-plans/<int:plan_id>/", trainer_nutrition_plan_detail_page, name="trainer-nutrition-plan-detail"),
    path("dashboard/nutrition-plans/<int:plan_id>/update/", dashboard_update_nutrition_plan, name="dashboard-update-nutrition-plan"),
    path("dashboard/nutrition-plans/<int:plan_id>/delete/", dashboard_delete_nutrition_plan, name="dashboard-delete-nutrition-plan"),
    path("dashboard/nutrition-plans/<int:plan_id>/duplicate/", dashboard_duplicate_nutrition_plan, name="dashboard-duplicate-nutrition-plan"),
    path("dashboard/nutrition-plans/<int:plan_id>/meals/create/", dashboard_create_nutrition_meal, name="dashboard-create-nutrition-meal"),
    path("dashboard/nutrition-plans/<int:plan_id>/meals/<int:meal_id>/update/", dashboard_update_nutrition_meal, name="dashboard-update-nutrition-meal"),
    path("dashboard/nutrition-plans/<int:plan_id>/meals/<int:meal_id>/delete/", dashboard_delete_nutrition_meal, name="dashboard-delete-nutrition-meal"),
    path("dashboard/nutrition-plans/<int:plan_id>/meal-items/create/", dashboard_add_food_to_nutrition_meal, name="dashboard-add-food-to-nutrition-meal"),
    path("dashboard/nutrition-plans/<int:plan_id>/meal-items/<int:item_id>/delete/", dashboard_delete_nutrition_meal_item, name="dashboard-delete-nutrition-meal-item"),

    path("dashboard/checkin-forms/", trainer_checkin_forms_page, name="trainer-checkin-forms-page"),
    path("dashboard/checkin-forms/create/", dashboard_create_checkin_form, name="dashboard-create-checkin-form"),
    path("dashboard/checkin-forms/<int:form_id>/", trainer_checkin_form_detail_page, name="trainer-checkin-form-detail"),
    path("dashboard/checkin-forms/<int:form_id>/update/", dashboard_update_checkin_form, name="dashboard-update-checkin-form"),
    path("dashboard/checkin-forms/<int:form_id>/delete/", dashboard_delete_checkin_form, name="dashboard-delete-checkin-form"),
    path("dashboard/checkin-forms/<int:form_id>/questions/create/", dashboard_create_checkin_question, name="dashboard-create-checkin-question"),
    path("dashboard/checkin-forms/<int:form_id>/questions/<int:question_id>/update/", dashboard_update_checkin_question, name="dashboard-update-checkin-question"),
    path("dashboard/checkin-forms/<int:form_id>/questions/<int:question_id>/delete/", dashboard_delete_checkin_question, name="dashboard-delete-checkin-question"),

    # Site (Phase 7) — public landing page editor
    path("dashboard/site/", trainer_site_page, name="trainer-site-page"),

    # New scaffolds
    path("dashboard/activity/", trainer_activity_page, name="trainer-activity-page"),
    path("dashboard/settings/", trainer_settings_page, name="trainer-settings-page"),
    path("dashboard/settings/profile/", dashboard_update_profile, name="dashboard-update-profile"),
    path("dashboard/settings/check-slug/", dashboard_check_slug, name="dashboard-check-slug"),
    path("dashboard/settings/pricing/save/", dashboard_pricing_save, name="dashboard-pricing-save"),
    path("dashboard/settings/pricing/<int:plan_id>/delete/", dashboard_pricing_delete, name="dashboard-pricing-delete"),
    path("dashboard/settings/delete-account/", dashboard_delete_account, name="dashboard-delete-account"),

    # Logged-in password change (used by the Settings workspace)
    path(
        "portal/password-change/",
        auth_views.PasswordChangeView.as_view(
            template_name="auth/password_change.html",
            success_url="/portal/password-change/done/",
        ),
        name="password_change",
    ),
    path(
        "portal/password-change/done/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="auth/password_change_done.html",
        ),
        name="password_change_done",
    ),

    path(
        "portal/password-reset/",
        auth_views.PasswordResetView.as_view(
            template_name="auth/password_reset.html",
            email_template_name="auth/password_reset_email.txt",
            subject_template_name="auth/password_reset_subject.txt",
            success_url="/portal/password-reset/done/",
        ),
        name="password_reset",
    ),
    path(
        "portal/password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="auth/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "portal/reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="auth/password_reset_confirm.html",
            success_url="/portal/reset/done/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "portal/reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="auth/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
]
