# Generated by Django 4.2.30 on 2026-04-16 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
        ('users', '0002_clientprofile_assigned_workout_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='assigned_nutrition_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clients', to='nutrition.nutritionplan'),
        ),
    ]
