# Generated by Django 4.2.30 on 2026-04-29 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_dob_goal_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Changelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('audience', models.CharField(choices=[('trainers', 'Trainers'), ('clients', 'Clients'), ('all', 'Everyone')], default='trainers', max_length=10)),
                ('cta_url', models.CharField(blank=True, default='', max_length=255)),
                ('cta_label', models.CharField(blank=True, default='', max_length=80)),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Changelog entry',
                'verbose_name_plural': 'Changelog',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoachingTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='✦', help_text='Single glyph rendered before the tip title. Keep tasteful.', max_length=8)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('business', 'Business'), ('programming', 'Programming'), ('nutrition', 'Nutrition'), ('retention', 'Retention'), ('mindset', 'Mindset')], default='business', max_length=20)),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coaching tip',
                'verbose_name_plural': 'Coaching tips',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MagicLoginToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('requested_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('consumed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magic_login_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Magic-login token',
                'verbose_name_plural': 'Magic-login tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
